name: scan with KICS and upload JSON

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: Run KICS Scan with JSON result
        uses: checkmarx/kics-action@v1.2
        with:
          path: '../../'
          # when provided with a directory on output_path
          # it will generate the specified reports file named 'results.{extension}'
          # in this example it will generate:
          # - results-dir/results.json
          # - results-dir/results.sarif
          output_path: results-dir
          platform_type: terraform
          output_formats: 'json'
      - name: Show results
        run: |
          cat results-dir/results.json
      - name: Upload JSON file
        uses: github/codeql-action/upload-json@v1
        with:
          sarif_file: results-dir/results.json
